site_name: Anahit Melqonyan - Fab Academy
site_description: Fab Academy documentation site for Anahit Melqonyan
site_author: Anahit Melqonyan
copyright: Copyright 2026 Anahit Melqonyan - Creative Commons Attribution Non Commercial

site_url: https://anahitmelqonyan4565-bit.github.io/my-website/

theme:
  name: material
  highlightjs: true
  primary: blue grey
  accent: blue